--PUNTO 1: Crear un producto nuevo, ingresando su categoría y suplidor
--PUNTO 2: Identificar todos los suplidores que tienen la región en blanco y rellenar con el valor “N/A”
--PUNTO 3: Eliminar de la tabla de detalle de ordenes todos aquellos productos con valor 1
--PUNTO 4: Listar todos los registros de la tabla de territorios
